// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zkcebvvklnpwtgdfgbox.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InprY2VidnZrbG5wd3RnZGZnYm94Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA5OTc1MzQsImV4cCI6MjA1NjU3MzUzNH0.NAe2GC0wey0DBuhLz5J8VsHOKlNIrEVYN-T-DMU0S2E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);